sonar.organization=amithbharadwaj
sonar.projectKey=amithbharadwaj_aidy-flutter
sonar.projectName=Lokale Flutter
sonar.sourceEncoding=UTF-8

sonar.sources=lib
sonar.tests=test

sonar.exclusions=lib/firebase_options.dart,**/build/**,**/coverage/**
sonar.coverage.exclusions=lib/firebase_options.dart,lib/presentation/localization/static_content_translations.dart
sonar.cpd.exclusions=lib/presentation/localization/static_content_translations.dart

sonar.dart.lcov.reportPaths=coverage/lcov.info
